// Spore structures: only generate in #c:is_cold (Natural Temperature polar bands).
// KubeJS 1.21: WorldgenEvents disabled; override structure JSON via generateData (same pattern as oregen.js).
// Docs: https://kubejs.com/wiki/other/major-updates/7.0 — use datapacks / generateData instead of WorldgenEvents
ServerEvents.generateData("after_mods", event => {
    const structures = {
        "biomass_tower": {"type":"minecraft:jigsaw","start_pool":"spore:biomass_tower/start_pool","size":2,"max_distance_from_center":1,"biomes":"#c:is_cold","step":"surface_structures","min_inclusive":{"above_bottom":32},"start_height":{"absolute":-1},"project_start_to_heightmap":"WORLD_SURFACE_WG","use_expansion_hack":false,"spawn_overrides":{"creature":{"bounding_box":"piece","spawns":[{"type":"spore:inf_human","weight":1,"minCount":1,"maxCount":4}]}}},
        "cathedral": {"type":"minecraft:jigsaw","start_pool":"spore:cathedral/start_pool","size":2,"max_distance_from_center":1,"biomes":"#c:is_cold","step":"surface_structures","min_inclusive":{"above_bottom":32},"start_height":{"absolute":-20},"project_start_to_heightmap":"WORLD_SURFACE_WG","use_expansion_hack":false,"spawn_overrides":{"creature":{"bounding_box":"piece","spawns":[{"type":"spore:inf_human","weight":40,"minCount":1,"maxCount":4},{"type":"spore:inf_villager","weight":40,"minCount":1,"maxCount":4}]}}},
        "cell": {"type":"minecraft:jigsaw","start_pool":"spore:cell/start_pool","size":2,"max_distance_from_center":1,"biomes":"#c:is_cold","step":"surface_structures","min_inclusive":{"above_bottom":32},"start_height":{"absolute":-3},"project_start_to_heightmap":"WORLD_SURFACE_WG","use_expansion_hack":false,"spawn_overrides":{"creature":{"bounding_box":"piece","spawns":[{"type":"spore:inf_human","weight":40,"minCount":1,"maxCount":4},{"type":"spore:inf_villager","weight":40,"minCount":1,"maxCount":4}]}}},
        "celltower": {"type":"minecraft:jigsaw","start_pool":"spore:celltower/start_pool","size":2,"max_distance_from_center":1,"biomes":"#c:is_cold","step":"surface_structures","min_inclusive":{"above_bottom":32},"start_height":{"absolute":-5},"project_start_to_heightmap":"WORLD_SURFACE_WG","use_expansion_hack":false,"spawn_overrides":{"creature":{"bounding_box":"piece","spawns":[{"type":"spore:inf_human","weight":40,"minCount":1,"maxCount":4},{"type":"spore:inf_villager","weight":40,"minCount":1,"maxCount":4}]}}},
        "church": {"type":"minecraft:jigsaw","start_pool":"spore:church/start_pool","size":2,"max_distance_from_center":1,"biomes":"#c:is_cold","step":"surface_structures","min_inclusive":{"above_bottom":32},"start_height":{"absolute":-3},"project_start_to_heightmap":"WORLD_SURFACE_WG","use_expansion_hack":false,"spawn_overrides":{"creature":{"bounding_box":"piece","spawns":[{"type":"spore:inf_human","weight":40,"minCount":1,"maxCount":4},{"type":"spore:inf_villager","weight":40,"minCount":1,"maxCount":4}]}}},
        "hospital": {"type":"minecraft:jigsaw","start_pool":"spore:hospital/start_pool","size":3,"max_distance_from_center":1,"biomes":"#c:is_cold","step":"surface_structures","min_inclusive":{"above_bottom":32},"start_height":{"absolute":-9},"project_start_to_heightmap":"WORLD_SURFACE_WG","use_expansion_hack":false,"spawn_overrides":{"creature":{"bounding_box":"piece","spawns":[{"type":"spore:inf_human","weight":40,"minCount":1,"maxCount":4},{"type":"spore:inf_villager","weight":40,"minCount":1,"maxCount":4}]}}},
        "iceberg_mines": {"type":"minecraft:jigsaw","start_pool":"spore:iceberg_mines/start_pool","size":2,"max_distance_from_center":1,"biomes":"#c:is_cold","step":"surface_structures","min_inclusive":{"above_bottom":32},"start_height":{"absolute":-5},"project_start_to_heightmap":"WORLD_SURFACE_WG","use_expansion_hack":false,"spawn_overrides":{"creature":{"bounding_box":"piece","spawns":[{"type":"minecraft:snow_golem","weight":40,"minCount":1,"maxCount":4}]}}},
        "lab": {"type":"minecraft:jigsaw","start_pool":"spore:lab/start_pool","size":1,"max_distance_from_center":1,"biomes":"#c:is_cold","step":"surface_structures","min_inclusive":{"above_bottom":32},"start_height":{"absolute":-17},"project_start_to_heightmap":"WORLD_SURFACE_WG","use_expansion_hack":false,"spawn_overrides":{"creature":{"bounding_box":"piece","spawns":[{"type":"spore:inf_hazmat","weight":70,"minCount":1,"maxCount":4}]}}},
        "lodge": {"type":"minecraft:jigsaw","start_pool":"spore:lodge/start_pool","size":2,"max_distance_from_center":1,"biomes":"#c:is_cold","step":"surface_structures","min_inclusive":{"above_bottom":32},"start_height":{"absolute":-8},"project_start_to_heightmap":"WORLD_SURFACE_WG","use_expansion_hack":false,"spawn_overrides":{"creature":{"bounding_box":"piece","spawns":[{"type":"spore:inf_human","weight":40,"minCount":1,"maxCount":4},{"type":"spore:inf_villager","weight":40,"minCount":1,"maxCount":4}]}}},
        "mass_grave": {"type":"minecraft:jigsaw","start_pool":"spore:mass_grave/start_pool","size":2,"max_distance_from_center":1,"biomes":"#c:is_cold","step":"surface_structures","min_inclusive":{"above_bottom":32},"start_height":{"absolute":-5},"project_start_to_heightmap":"WORLD_SURFACE_WG","use_expansion_hack":false,"spawn_overrides":{"creature":{"bounding_box":"piece","spawns":[{"type":"spore:inf_human","weight":1,"minCount":1,"maxCount":4}]}}},
        "military_camp": {"type":"minecraft:jigsaw","start_pool":"spore:military_camp/start_pool","size":2,"max_distance_from_center":1,"biomes":"#c:is_cold","step":"surface_structures","min_inclusive":{"above_bottom":32},"start_height":{"absolute":-11},"project_start_to_heightmap":"WORLD_SURFACE_WG","use_expansion_hack":false,"spawn_overrides":{"creature":{"bounding_box":"piece","spawns":[{"type":"spore:inf_human","weight":40,"minCount":1,"maxCount":4},{"type":"spore:inf_villager","weight":40,"minCount":1,"maxCount":4}]}}},
        "mines": {"type":"minecraft:jigsaw","start_pool":"spore:mines/start_pool","size":1,"max_distance_from_center":1,"biomes":"#c:is_cold","step":"surface_structures","min_inclusive":{"above_bottom":32},"start_height":{"absolute":-9},"project_start_to_heightmap":"WORLD_SURFACE_WG","use_expansion_hack":false,"spawn_overrides":{"creature":{"bounding_box":"piece","spawns":[{"type":"spore:inf_hazmat","weight":70,"minCount":1,"maxCount":4}]}}},
        "prison": {"type":"minecraft:jigsaw","start_pool":"spore:prison/start_pool","size":2,"max_distance_from_center":1,"biomes":"#c:is_cold","step":"surface_structures","min_inclusive":{"above_bottom":32},"start_height":{"absolute":-28},"project_start_to_heightmap":"WORLD_SURFACE_WG","use_expansion_hack":false,"spawn_overrides":{"creature":{"bounding_box":"piece","spawns":[{"type":"spore:inf_human","weight":40,"minCount":1,"maxCount":4},{"type":"spore:inf_villager","weight":40,"minCount":1,"maxCount":4}]}}},
    }
    for (let id in structures) {
        event.json("spore:worldgen/structure/" + id, structures[id])
    }
})
