if (Platform.isLoaded("createdieselgenerators")) {
    if (typeof RecipeViewerEvents !== "undefined") RecipeViewerEvents.removeEntries("item", event => {
        const hide = (entry) => event.remove(entry)
        hide("createdieselgenerators:crude_oil_bucket")
        hide("createdieselgenerators:gasoline_bucket")
        hide("createdieselgenerators:diesel_bucket")
        hide("createdieselgenerators:biodiesel_bucket")
        hide("createdieselgenerators:plant_oil_bucket")
    })
    else if (typeof JEIEvents !== "undefined") JEIEvents.hideItems(event => {
        event.hide("createdieselgenerators:crude_oil_bucket")
        event.hide("createdieselgenerators:gasoline_bucket")
        event.hide("createdieselgenerators:diesel_bucket")
        event.hide("createdieselgenerators:biodiesel_bucket")
        event.hide("createdieselgenerators:plant_oil_bucket")
    })
    if (typeof RecipeViewerEvents !== "undefined") RecipeViewerEvents.removeEntries("fluid", event => {
        const hide = (entry) => event.remove(entry)
        hide("createdieselgenerators:crude_oil")
        hide("createdieselgenerators:flowing_crude_oil")
        hide("createdieselgenerators:gasoline")
        hide("createdieselgenerators:flowing_gasoline")
        hide("createdieselgenerators:diesel")
        hide("createdieselgenerators:flowing_diesel")
        hide("createdieselgenerators:biodiesel")
        hide("createdieselgenerators:flowing_biodiesel")
        hide("createdieselgenerators:plant_oil")
        hide("createdieselgenerators:flowing_plant_oil")
    })
    else if (typeof JEIEvents !== "undefined") JEIEvents.hideFluids(event => {
        event.hide("createdieselgenerators:crude_oil")
        event.hide("createdieselgenerators:flowing_crude_oil")
        event.hide("createdieselgenerators:gasoline")
        event.hide("createdieselgenerators:flowing_gasoline")
        event.hide("createdieselgenerators:diesel")
        event.hide("createdieselgenerators:flowing_diesel")
        event.hide("createdieselgenerators:biodiesel")
        event.hide("createdieselgenerators:flowing_biodiesel")
        event.hide("createdieselgenerators:plant_oil")
        event.hide("createdieselgenerators:flowing_plant_oil")
    })
}
